### ISSUE TITLE
Logs throwing errors on startup after migration

### ISSUE THREAD

**Issue by elvece** [Start9Labs/synapse-wrapper#23]
EOS 0.2.17 version of synapse was 1.36.0

EOS 0.3.0 version of synapse is 1.42.0

```

2021-12-22T07:06:04.450346Z 2021-12-22 07:06:04,449 - root - 336 - WARNING - main - ***** STARTING SERVER *****
2021-12-22T07:06:04.450886Z 2021-12-22 07:06:04,450 - root - 337 - WARNING - main - Server /usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.42.0
2021-12-22T07:06:04.451276Z 2021-12-22 07:06:04,450 - root - 338 - INFO - main - Server hostname: wr5bumrkyhtsh6roigttxtuahkol7gzq6n7ufdijc5lhkf3oy53dbtqd.onion
2021-12-22T07:06:04.451685Z 2021-12-22 07:06:04,450 - root - 339 - INFO - main - Instance name: master
2021-12-22T07:06:04.452059Z 2021-12-22 07:06:04,451 - synapse.app.homeserver - 357 - INFO - main - Setting up server
2021-12-22T07:06:04.452418Z 2021-12-22 07:06:04,451 - synapse.server - 308 - INFO - main - Setting up.
2021-12-22T07:06:04.460986Z 2021-12-22 07:06:04,460 - synapse.storage.databases - 49 - INFO - main - [database config 'master']: Checking database server
2021-12-22T07:06:04.461622Z 2021-12-22 07:06:04,460 - synapse.storage.databases - 52 - INFO - main - [database config 'master']: Preparing for databases ['main', 'state']
2021-12-22T07:06:04.462356Z 2021-12-22 07:06:04,461 - synapse.storage.prepare_database - 116 - INFO - main - ['main', 'state']: Checking existing schema version
2021-12-22T07:06:04.474862Z 2021-12-22 07:06:04,469 - synapse.app._base - 161 - ERROR - main - Exception during startup
2021-12-22T07:06:04.475371Z Traceback (most recent call last):
2021-12-22T07:06:04.475784Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 360, in setup
2021-12-22T07:06:04.476123Z     hs.setup()
2021-12-22T07:06:04.476432Z   File "/usr/local/lib/python3.8/site-packages/synapse/server.py", line 310, in setup
2021-12-22T07:06:04.476690Z     self.datastores = Databases(self.DATASTORE_CLASS, self)
2021-12-22T07:06:04.476902Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 57, in __init__
2021-12-22T07:06:04.477259Z     prepare_database(
2021-12-22T07:06:04.477538Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 117, in prepare_database
2021-12-22T07:06:04.477821Z     version_info = _get_or_create_schema_state(cur, database_engine)
2021-12-22T07:06:04.478107Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 656, in _get_or_create_schema_state
2021-12-22T07:06:04.478405Z     executescript(txn, sql_path)
2021-12-22T07:06:04.478776Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 643, in executescript
2021-12-22T07:06:04.479170Z     execute_statements_from_stream(txn, f)
2021-12-22T07:06:04.479452Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 648, in execute_statements_from_stream
2021-12-22T07:06:04.479753Z     cur.execute(statement)
2021-12-22T07:06:04.480139Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 298, in execute
2021-12-22T07:06:04.480598Z     self._do_execute(self.txn.execute, sql, *args)
2021-12-22T07:06:04.481044Z   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 331, in _do_execute
2021-12-22T07:06:04.482508Z     return func(sql, *args)
2021-12-22T07:06:04.482918Z sqlite3.OperationalError: attempt to write a readonly database
2021-12-22T07:06:04.483296Z ********************************************
2021-12-22T07:06:04.483672Z  Error during initialisation:
2021-12-22T07:06:04.484070Z     attempt to write a readonly database
2021-12-22T07:06:04.484422Z  There may be more information in the logs.
2021-12-22T07:06:04.484709Z ********************************************
2021-12-22T07:06:13.425849Z This server is configured to use 'matrix.org' as its trusted key server via the
2021-12-22T07:06:13.427238Z 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
2021-12-22T07:06:13.427570Z server since it is long-lived, stable and trusted. However, some admins may
2021-12-22T07:06:13.427807Z wish to use another server for this purpose.
2021-12-22T07:06:13.428106Z 
2021-12-22T07:06:13.428382Z To suppress this warning and continue using 'matrix.org', admins should set
2021-12-22T07:06:13.428640Z 'suppress_key_server_warning' to 'true' in homeserver.yaml.
```

**Comment by chrisguida** [comment]
This appears to be happening because synapse expects some of its files to be owned by user `991` rather than `root`. Here's the synapse permissions before migration:

```
root@start9-8d7bdd8b:~# ls -al volumes/
bitcoind/      btcpayserver/  btc-rpc-proxy/ c-lightning/   lnd/           spark-wallet/  synapse/       thunderhub/    
root@start9-8d7bdd8b:~# ls -al volumes/synapse/
total 5076
drwxr-xr-x  4  991  991    4096 Dec 29 22:19 .
drwxr-xr-x 10 root root    4096 Dec 25 18:22 ..
-rw-r--r--  1 root root     985 Dec 25 18:27 cert.pem
-rw-r--r--  1  991  991 5160960 Dec 29 22:19 homeserver.db
-rw-r--r--  1  991  991    1769 Dec 28 16:25 homeserver.yaml
-rw-------  1 root root    1704 Dec 25 18:27 key.pem
drwxr-xr-x  4  991  991    4096 Dec 25 18:35 media_store
-rw-r--r--  1 root root     468 Dec 25 18:27 mvfpwfbd6tpqi46gzueyasugkhxzs7773n72542raxwngfw7ypb2w2ad.onion.log.config
-rw-r--r--  1  991  991      59 Dec 25 18:27 mvfpwfbd6tpqi46gzueyasugkhxzs7773n72542raxwngfw7ypb2w2ad.onion.signing.key
drwxr-xr-x  2 root root    4096 Dec 25 18:27 start9
```

and here's after:

```
root@embassy:/embassy-data/package-data/volumes/synapse/data/main# ll
total 5076
drwxr-xr-x 4 root root    4096 Dec 29 22:35 ./
drwxr-xr-x 3 root root    4096 Dec 29 22:35 ../
-rw-r--r-- 1 root root     985 Dec 29 22:35 cert.pem
-rw-r--r-- 1 root root 5160960 Dec 29 22:35 homeserver.db
-rw-r--r-- 1 root root    1769 Dec 29 22:35 homeserver.yaml
-rw------- 1 root root    1704 Dec 29 22:35 key.pem
drwxr-xr-x 4 root root    4096 Dec 29 22:35 media_store/
-rw-r--r-- 1 root root     468 Dec 29 22:35 mvfpwfbd6tpqi46gzueyasugkhxzs7773n72542raxwngfw7ypb2w2ad.onion.log.config
-rw-r--r-- 1 root root      59 Dec 29 22:35 mvfpwfbd6tpqi46gzueyasugkhxzs7773n72542raxwngfw7ypb2w2ad.onion.signing.key
drwxr-xr-x 2 root root    4096 Dec 29 22:35 start9/
```

@dr-bonez can we add a feature to preserve file ownership attributes?

**Comment by chrisguida** [comment]
Fixed
