### ISSUE TITLE
Synapse reports crashing every 15 minutes.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/synapse-wrapper#24]
![Screen Shot 2022-01-21 at 2 34 34 PM](https://user-images.githubusercontent.com/45926711/150609059-8ea94f6a-cf8f-42ee-b246-19922ece07ec.png)
![Screen Shot 2022-01-21 at 2 34 40 PM](https://user-images.githubusercontent.com/45926711/150609066-e2c6c3f2-2418-4e6f-9cd4-9a54aab04d1c.png)

Unsure of steps to reproduce.

This is on my prod box, migrated from 0.2x box than ran off an SSD.

**Comment by BitcoinMechanic** [comment]
From the logs:

```
2022-01-21T22:32:09.869604Z This server is configured to use 'matrix.org' as its trusted key server via the
2022-01-21T22:32:09.871810Z 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
2022-01-21T22:32:09.872289Z server since it is long-lived, stable and trusted. However, some admins may
2022-01-21T22:32:09.872728Z wish to use another server for this purpose.
2022-01-21T22:32:09.873072Z 
2022-01-21T22:32:09.875214Z To suppress this warning and continue using 'matrix.org', admins should set
2022-01-21T22:32:09.876164Z 'suppress_key_server_warning' to 'true' in homeserver.yaml.
2022-01-21T22:32:09.876945Z --------------------------------------------------------------------------------
2022-01-21T22:32:10.118955Z Traceback (most recent call last):
2022-01-21T22:32:10.120641Z   File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
2022-01-21T22:32:10.122021Z     handler = self.configure_handler(handlers[name])
2022-01-21T22:32:10.123093Z   File "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
2022-01-21T22:32:10.124066Z     result = factory(**kwargs)
2022-01-21T22:32:10.125150Z   File "/usr/local/lib/python3.8/logging/handlers.py", line 200, in __init__
2022-01-21T22:32:10.126270Z     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
2022-01-21T22:32:10.127658Z   File "/usr/local/lib/python3.8/logging/handlers.py", line 55, in __init__
2022-01-21T22:32:10.128784Z     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
2022-01-21T22:32:10.130278Z   File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
2022-01-21T22:32:10.131296Z     StreamHandler.__init__(self, self._open())
2022-01-21T22:32:10.132419Z   File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
2022-01-21T22:32:10.133658Z     return open(self.baseFilename, self.mode, encoding=self.encoding)
2022-01-21T22:32:10.135625Z PermissionError: [Errno 13] Permission denied: '/data/homeserver.log'
2022-01-21T22:32:10.137371Z 
2022-01-21T22:32:10.139236Z The above exception was the direct cause of the following exception:
2022-01-21T22:32:10.140664Z 
2022-01-21T22:32:10.142254Z Traceback (most recent call last):
2022-01-21T22:32:10.143780Z   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-21T22:32:10.145405Z     return _run_code(code, main_globals, None,
2022-01-21T22:32:10.146944Z   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-21T22:32:10.148280Z     exec(code, run_globals)
2022-01-21T22:32:10.149799Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 462, in 
2022-01-21T22:32:10.151047Z     main()
2022-01-21T22:32:10.152262Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 452, in main
2022-01-21T22:32:10.153813Z     hs = setup(sys.argv[1:])
2022-01-21T22:32:10.155007Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 355, in setup
2022-01-21T22:32:10.156265Z     synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
2022-01-21T22:32:10.157652Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 329, in setup_logging
2022-01-21T22:32:10.158806Z     _setup_stdlib_logging(config, log_config_path, logBeginner=logBeginner)
2022-01-21T22:32:10.160086Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 217, in _setup_stdlib_logging
2022-01-21T22:32:10.161313Z     _load_logging_config(log_config_path)
2022-01-21T22:32:10.162683Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/logger.py", line 293, in _load_logging_config
2022-01-21T22:32:10.164021Z     logging.config.dictConfig(log_config)
2022-01-21T22:32:10.165259Z   File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
2022-01-21T22:32:10.166558Z     dictConfigClass(config).configure()
2022-01-21T22:32:10.167792Z   File "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
2022-01-21T22:32:10.169403Z     raise ValueError('Unable to configure handler '
2022-01-21T22:32:10.170725Z ValueError: Unable to configure handler 'file'
2022-01-21T22:32:23.025523Z This server is configured to use 'matrix.org' as its trusted key server via the
2022-01-21T22:32:23.027520Z 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
2022-01-21T22:32:23.027954Z server since it is long-lived, stable and trusted. However, some admins may
2022-01-21T22:32:23.028293Z wish to use another server for this purpose.
```

**Comment by BitcoinMechanic** [comment]
This was fixed by changing `chown`ing to copy what is in here: https://github.com/Start9Labs/synapse-wrapper/issues/23#issuecomment-1002805008

Unsure if this is due to my CIFS migration via linux VM -> mac potentially messing stuff up.
